Outfits = {
    male = {
        { componentId = CLOTHING_COMPONENTS.SHIRT,      drawableId = 15,                         textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.BODY,       drawableId = 238,                        textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.BODY_ARMOR, drawableId = 0,                          textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.DECALS,     drawableId = 0,                          textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.ARMS,       drawableId = 15,                         textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.PANTS,      drawableId = 64,                         textureId = 4 },
        { componentId = CLOTHING_COMPONENTS.SHOES,      drawableId = 27,                         textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.BAGS_AND_PARACHUTE,      drawableId =  DRAWABLE.NONE,                         textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.MASKS,      drawableId =  DRAWABLE.NONE,                         textureId = 0 },
        { isProp = true,                                componentId = PROP_COMPONENTS.HATS,      drawableId = DRAWABLE.NONE, textureId = 0 },
        { isProp = true,                                componentId = CLOTHING_COMPONENTS.MASKS, drawableId = DRAWABLE.NONE,             textureId = 0 },
        { isProp = true,                                componentId = PROP_COMPONENTS.EARS,      drawableId = DRAWABLE.NONE,             textureId = 0 },
        { isProp = true,                                componentId = PROP_COMPONENTS.WATCHES,   drawableId = DRAWABLE.NONE,             textureId = 0 },
        { isProp = true,                                componentId = PROP_COMPONENTS.BRACELETS, drawableId = DRAWABLE.NONE,             textureId = 0 },
    },
    female = {
        { componentId = CLOTHING_COMPONENTS.SHIRT,      drawableId = 15,                         textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.BODY,       drawableId = 23,                         textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.DECALS,     drawableId = 0,                          textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.BODY_ARMOR, drawableId = 0,                          textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.ARMS,       drawableId = 12,                         textureId = 0 },
        { componentId = CLOTHING_COMPONENTS.PANTS,      drawableId = 58,                         textureId = 1 },
        { componentId = CLOTHING_COMPONENTS.SHOES,      drawableId = 27,                         textureId = 0 },
        { isProp = true,                                componentId = PROP_COMPONENTS.HATS,      drawableId = DRAWABLE.NONE, textureId = 0 },
        { isProp = true,                                componentId = CLOTHING_COMPONENTS.MASKS, drawableId = DRAWABLE.NONE,             textureId = 0 },
        { isProp = true,                                componentId = PROP_COMPONENTS.EARS,      drawableId = DRAWABLE.NONE,             textureId = 0 },
        { isProp = true,                                componentId = PROP_COMPONENTS.WATCHES,   drawableId = DRAWABLE.NONE,             textureId = 0 },
        { isProp = true,                                componentId = PROP_COMPONENTS.BRACELETS, drawableId = DRAWABLE.NONE,             textureId = 0 },
    }
}
