while not Config do Citizen.Wait(1) end

-- Shop locations are defined in maps/departments/*.lua under `vehicleShops`.
-- Addon fleet: gb_vehicles_pd_ems + gb_vehicles_pd_ems2 (Gabz PD pack)
Config.VehicleShop = {
    ---@field Enabled: boolean [master toggle for the police vehicle shop feature]
    Enabled = true,

    ---@field Vehicles: table [purchasable vehicles grouped by category]
    Vehicles = {
        ['patrol'] = {
            {
                id = 'gbpolstanier',
                name = 'Stanier LE Police',
                model = 'gbpolstanier',
                price = 12500,
                armor = 0,
                description = 'Podstawowy radiowóz patrolowy LSPD.',
                rank = 'KADET',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 1, ['sheriff'] = 1 },
            },
            {
                id = 'gbpoladmiral',
                name = 'Admiral Police',
                model = 'gbpoladmiral',
                price = 15000,
                armor = 0,
                description = 'Ekonomiczny sedan służbowy na patrole dzielnicowe.',
                rank = 'KADET',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 1, ['sheriff'] = 1 },
            },
            {
                id = 'gbpolimpaler',
                name = 'Impaler Police',
                model = 'gbpolimpaler',
                price = 18000,
                armor = 0,
                description = 'Muscle patrol — szybki dojazd na interwencje.',
                rank = 'OFICER I',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 2, ['sheriff'] = 2 },
            },
            {
                id = 'gbpolargento7f',
                name = 'Argento 7F Police',
                model = 'gbpolargento7f',
                price = 22000,
                armor = 1,
                description = 'Komfortowy sedan uniwersalny dla patrolu.',
                rank = 'OFICER II',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 3, ['sheriff'] = 3 },
            },
            {
                id = 'gbpolesperta',
                name = 'Rumpo Esperta Police',
                model = 'gbpolesperta',
                price = 24000,
                armor = 0,
                description = 'Van patrolowy / transport ekipy.',
                rank = 'OFICER III',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 4, ['sheriff'] = 4 },
            },
            {
                id = 'gbpolsteedvan',
                name = 'Steed Police Van',
                model = 'gbpolsteedvan',
                price = 26000,
                armor = 0,
                description = 'Van transportowy na dłuższe zmiany.',
                rank = 'OFICER III+1',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 5, ['sheriff'] = 5 },
            },
        },

        ['suv'] = {
            {
                id = 'gbpolscoutgsx',
                name = 'Scout GSX Police',
                model = 'gbpolscoutgsx',
                price = 32000,
                armor = 1,
                description = 'Kompaktowy SUV patrolowy.',
                rank = 'SIERZANT I',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 6, ['sheriff'] = 6 },
            },
            {
                id = 'gbpolgresley',
                name = 'Gresley Police',
                model = 'gbpolgresley',
                price = 35000,
                armor = 1,
                description = 'Uniwersalny SUV na patrole miejskie.',
                rank = 'SIERZANT II',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 7, ['sheriff'] = 7 },
            },
            {
                id = 'gbpolbisonstx',
                name = 'Bison STX Police',
                model = 'gbpolbisonstx',
                price = 38000,
                armor = 2,
                description = 'Pickup STX — teren i dojazd off-road.',
                rank = 'SIERZANT III',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 8, ['sheriff'] = 8 },
            },
            {
                id = 'gbpolbisonhf',
                name = 'Bison HF Police',
                model = 'gbpolbisonhf',
                price = 42000,
                armor = 2,
                description = 'Mocniejsza wersja pickupa patrolowego.',
                rank = 'PORUCZNIK I',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 9, ['sheriff'] = 9 },
            },
            {
                id = 'gbpolhedra',
                name = 'Hedra Kombi Police',
                model = 'gbpolhedra',
                price = 40000,
                armor = 1,
                description = 'Kombi na dłuższe patrole i transport.',
                rank = 'PORUCZNIK I',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 9, ['sheriff'] = 9 },
            },
            {
                id = 'gbpolmojave',
                name = 'Mojave Police',
                model = 'gbpolmojave',
                price = 48000,
                armor = 2,
                description = 'Duży SUV terenowy dla jednostek specjalnych.',
                rank = 'PORUCZNIK II',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 10, ['sheriff'] = 10 },
            },
        },

        ['interceptor'] = {
            {
                id = 'gbpolclubxr',
                name = 'Club XR Police',
                model = 'gbpolclubxr',
                price = 52000,
                armor = 1,
                description = 'Lekki hot hatch do pościgów miejskich.',
                rank = 'PORUCZNIK II',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 10, ['sheriff'] = 10 },
            },
            {
                id = 'gbpolcometcl',
                name = 'Comet CL Police',
                model = 'gbpolcometcl',
                price = 58000,
                armor = 1,
                description = 'Sportowy coupe patrolowy.',
                rank = 'PORUCZNIK III',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 11, ['sheriff'] = 11 },
            },
            {
                id = 'gbpolsentinelgts',
                name = 'Sentinel GTS-R Police',
                model = 'gbpolsentinelgts',
                price = 62000,
                armor = 1,
                description = 'Sedan sportowy klasy GT.',
                rank = 'PORUCZNIK III',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 11, ['sheriff'] = 11 },
            },
            {
                id = 'gbpolsultanrsx',
                name = 'Sultan RSx Police',
                model = 'gbpolsultanrsx',
                price = 68000,
                armor = 1,
                description = 'AWD interceptor — pościgi w każdych warunkach.',
                rank = 'KAPITAN I',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 12, ['sheriff'] = 12 },
            },
            {
                id = 'gbpoldomgsx',
                name = 'Dominator GSX Police',
                model = 'gbpoldomgsx',
                price = 75000,
                armor = 2,
                description = 'Muscle interceptor o wysokiej prędkości.',
                rank = 'KAPITAN I',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 12, ['sheriff'] = 12 },
            },
            {
                id = 'gbpolcomets2r',
                name = 'Comet S2R Police',
                model = 'gbpolcomets2r',
                price = 82000,
                armor = 1,
                description = 'Super sport dla jednostek pościgowych.',
                rank = 'KAPITAN II',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 13, ['sheriff'] = 13 },
            },
            {
                id = 'gbpolsolace',
                name = 'Solace Police',
                model = 'gbpolsolace',
                price = 85000,
                armor = 1,
                description = 'Luksusowy sedan pościgowy.',
                rank = 'KAPITAN III',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 14, ['sheriff'] = 14 },
            },
            {
                id = 'gbpolbanshees',
                name = 'Banshee S Police',
                model = 'gbpolbanshees',
                price = 92000,
                armor = 1,
                description = 'Sportowy interceptor klasy S.',
                rank = 'KOMENDANT',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 15, ['sheriff'] = 15 },
            },
            {
                id = 'gbpoltahomagt',
                name = 'Tahoma GT Police',
                model = 'gbpoltahomagt',
                price = 95000,
                armor = 1,
                description = 'Muscle GT na autostradowe pościgi.',
                rank = 'KOMENDANT',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 15, ['sheriff'] = 15 },
            },
            {
                id = 'gbpolechelon',
                name = 'Echelon Police',
                model = 'gbpolechelon',
                price = 98000,
                armor = 2,
                description = 'Sedan klasy executive dla jednostek specjalnych.',
                rank = 'ZASTĘPCA SZEFA',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 16, ['sheriff'] = 16 },
            },
            {
                id = 'gbpoleon',
                name = 'Eon Police',
                model = 'gbpoleon',
                price = 102000,
                armor = 1,
                description = 'Elektryczny interceptor — cichy pościg.',
                rank = 'ZASTĘPCA SZEFA',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 16, ['sheriff'] = 16 },
            },
            {
                id = 'gbpolturismogt',
                name = 'Turismo 300GT Police',
                model = 'gbpolturismogt',
                price = 125000,
                armor = 1,
                description = 'Supercar dla najwyższych rang — pościgi ekstremalne.',
                rank = 'CHIEF OF POLICE',
                allowedJobs = { 'police' },
                allowedGrades = { ['police'] = 18 },
            },
            {
                id = 'gbpoltr3s',
                name = 'TR3-S Police',
                model = 'gbpoltr3s',
                price = 135000,
                armor = 1,
                description = 'Hypercar interceptor — szczyt floty LSPD.',
                rank = 'CHIEF OF POLICE',
                allowedJobs = { 'police' },
                allowedGrades = { ['police'] = 18 },
            },
        },

        ['tactical'] = {
            {
                id = 'gbpolprospero',
                name = 'Prospero Police',
                model = 'gbpolprospero',
                price = 88000,
                armor = 3,
                description = 'SUV taktyczny dla operacji specjalnych.',
                rank = 'KAPITAN III',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 14, ['sheriff'] = 14 },
            },
            {
                id = 'gbpolstarlight',
                name = 'Starlight Police',
                model = 'gbpolstarlight',
                price = 95000,
                armor = 3,
                description = 'Van taktyczny z wzmocnioną kabiną.',
                rank = 'KOMENDANT',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 15, ['sheriff'] = 15 },
            },
            {
                id = 'gbpolterrorizer',
                name = 'Terrorizer Police',
                model = 'gbpolterrorizer',
                price = 145000,
                armor = 4,
                description = 'Opancerzony pojazd szturmowy SWAT.',
                rank = 'ASYSTENT SZEFA',
                allowedJobs = { 'police' },
                allowedGrades = { ['police'] = 17 },
            },
        },

        ['helicopter'] = {
            {
                id = 'polmav',
                name = 'Police Maverick',
                model = 'polmav',
                price = 750000,
                armor = 1,
                description = 'Jedyny helikopter służbowy — wsparcie powietrzne LSPD.',
                rank = 'KAPITAN II',
                allowedJobs = { 'police', 'sheriff' },
                allowedGrades = { ['police'] = 13, ['sheriff'] = 13 },
            },
        },
    },

    ---@field TestDrive: table [test drive settings]
    TestDrive = {
        enabled = true,
        duration = 60,
        spawnOffset = vector3(0, 5, 0),
        returnMessage = 'Your test drive has ended. The vehicle has been returned.',
    },
}
