-- cm-family v1.4.0 | durable family activity audit
CREATE TABLE IF NOT EXISTS `cm_family_activity_log` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_uid`       VARCHAR(96) NOT NULL,
  `family_id`       BIGINT UNSIGNED NOT NULL,
  `category`        VARCHAR(32) NOT NULL DEFAULT 'family',
  `action`          VARCHAR(64) NOT NULL,
  `severity`        VARCHAR(16) NOT NULL DEFAULT 'info',
  `high_risk`       TINYINT(1) NOT NULL DEFAULT 0,
  `status`          VARCHAR(16) NOT NULL DEFAULT 'success',
  `actor_cid`       VARCHAR(64) NULL,
  `actor_name`      VARCHAR(128) NULL,
  `target_cid`      VARCHAR(64) NULL,
  `target_name`     VARCHAR(128) NULL,
  `source_resource` VARCHAR(64) NOT NULL DEFAULT 'cm-family',
  `entity_type`     VARCHAR(32) NULL,
  `entity_id`       VARCHAR(96) NULL,
  `house_id`        BIGINT UNSIGNED NULL,
  `vehicle_id`      BIGINT UNSIGNED NULL,
  `amount`          BIGINT NULL,
  `detail`          JSON NULL,
  `created_at`      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_family_activity_uid` (`event_uid`),
  KEY `idx_family_activity_family_time` (`family_id`, `created_at`),
  KEY `idx_family_activity_high_time` (`high_risk`, `created_at`),
  KEY `idx_family_activity_action` (`action`),
  KEY `idx_family_activity_actor` (`actor_cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
