CREATE TABLE IF NOT EXISTS clothing_catalog (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    gender VARCHAR(16) NOT NULL DEFAULT 'male',
    component_type VARCHAR(16) NOT NULL DEFAULT 'component',
    component_index INT NOT NULL,
    drawable_id INT NOT NULL,
    texture_id INT NOT NULL DEFAULT -1,
    label VARCHAR(120) NULL,
    description TEXT NULL,
    price INT NOT NULL DEFAULT 0,
    category VARCHAR(80) NULL,
    shop VARCHAR(80) NULL,
    sleeve_style VARCHAR(30) NULL,
    arms INT NULL,
    arms_texture INT NOT NULL DEFAULT 0,
    undershirt INT NULL,
    undershirt_texture INT NOT NULL DEFAULT 0,
    bag_level INT NULL,
    backpack_slots INT NULL,
    max_weight INT NULL,
    image VARCHAR(255) NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    job VARCHAR(80) NULL,
    gang VARCHAR(80) NULL,
    notes TEXT NULL,
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_clothing_catalog (gender, component_type, component_index, drawable_id, texture_id),
    INDEX idx_shop (shop),
    INDEX idx_category (category),
    INDEX idx_enabled (enabled),
    INDEX idx_component (gender, component_index, drawable_id)
);
