const App={currentDialog:null,licenses:[],selectedLicense:null,adminLicenses:[],editingId:null};
const post=(name,body={})=>fetch(`https://cm-license/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const value=id=>document.getElementById(id).value.trim();
const formatNumber=n=>Number(n||0).toLocaleString();
window.addEventListener('message',({data})=>{if(!data?.type)return;if(data.type==='openLicenseMenu')openLicenseMenu(data);if(data.type==='showMyLicenses')showMyLicenses(data);if(data.type==='testResult')showTestResult(data);if(data.type==='openAdminMenu')openAdminMenu(data);if(data.type==='hideLoading')hideLoadingScreen();if(data.type==='npcInteraction'){const p=document.getElementById('npcInteraction');p.classList.toggle('hidden',!data.visible);if(data.visible){document.getElementById('npcInteractionName').textContent=data.name||'Alex Morgan';document.getElementById('npcInteractionRole').textContent=data.role||'CM License Instructor';}}if(data.type==='builderHint'){const h=document.getElementById('builderHint');h.textContent=data.message||'';h.classList.toggle('hidden',!data.message);}});
function closeDialog(id){document.getElementById(id)?.classList.add('hidden');App.currentDialog=null;}
function show(id){document.querySelectorAll('.dialog').forEach(e=>e.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');App.currentDialog=id;}
function showLoadingScreen(){show('loadingScreen');} function hideLoadingScreen(){document.getElementById('loadingScreen').classList.add('hidden');}
function closeMenu(){if(App.currentDialog)closeDialog(App.currentDialog);post('closeMenu');}
function openLicenseMenu(data){App.licenses=data.licenses||[];document.querySelector('#licenseMenu .header h1').textContent=data.instructorName||'Alex Morgan';document.querySelector('#licenseMenu .header p').textContent=`${data.instructorRole||'CM License Instructor'} · Which test would you like to take?`;document.querySelectorAll('#licenseMenu .option-btn[data-license]').forEach(b=>{const l=App.licenses.find(x=>x.license_type===b.dataset.license);b.classList.toggle('hidden',!l);if(l){b.querySelector('.label').textContent=l.label;b.querySelector('.price').textContent=`$${formatNumber(l.price)}`;b.onclick=()=>showTestConfirmation(l);}});document.getElementById('myLicensesBtn').onclick=()=>post('requestMyLicenses');document.getElementById('closeBtn').onclick=closeMenu;show('licenseMenu');}
function showTestConfirmation(data){App.selectedLicense=data.license_type||data.licenseType;document.getElementById('testTitle').textContent=`${data.label||App.selectedLicense} Test`;document.getElementById('testFee').textContent=`$${formatNumber(data.price)}`;document.getElementById('startTestBtn').onclick=()=>startTest(App.selectedLicense);show('testConfirmation');}
function startTest(licenseType){showLoadingScreen();post('startTest',{licenseType});} function cancelTest(){closeMenu();post('cancelTest');}
function showMyLicenses(data){const list=document.getElementById('licensesList');list.innerHTML='';(data.licenses||[]).forEach(l=>{const e=document.createElement('div');e.className='license-item';e.innerHTML=`<div class="license-item-title">${l.label}</div><div class="license-item-status ${l.status}">Status: ${String(l.status).toUpperCase()} | Expires: ${l.expiresAtDate||'N/A'}</div>`;list.appendChild(e);});if(!list.children.length)list.textContent='No licenses yet';show('myLicensesDialog');}
function showTestResult(data){const h=document.getElementById('resultHeader');h.classList.toggle('error',!data.passed);h.innerHTML=`<h1>${data.passed?'TEST PASSED':'TEST FAILED'}</h1>`;document.getElementById('resultMessage').textContent=data.passed?`You passed the ${data.licenseLabel||'license'} examination.`:(data.failReason||'Test failed');document.getElementById('resultDetails').textContent=data.message||(data.passed?`Valid for ${data.validDays} days.`:'Please try again.');show('testResult');}
function openAdminMenu(data){App.adminLicenses=data.licenses||[];const list=document.getElementById('adminLicensesList');list.innerHTML='';App.adminLicenses.forEach(l=>{const e=document.createElement('div');e.className='license-item';e.innerHTML=`<div class="license-item-title">${l.label}</div><div class="license-item-status">Route: ${l.route_configured?'Configured':'Not configured'}</div><div style="margin-top:8px"><button class="btn btn-primary" onclick="buildRoute(${l.id})">Set Up ${l.license_type==='driver'?'Car':l.license_type==='boat'?'Boat':'Air'} Route</button></div>`;list.appendChild(e);});show('adminMenu');}
function editLicense(id){const l=App.adminLicenses.find(x=>Number(x.id)===Number(id));if(!l)return;App.editingId=Number(id);document.getElementById('editorTitle').textContent='Edit License Test';const fields={licenseName:l.label,licenseType:l.license_type,licensePrice:l.price,licenseValidity:l.valid_days,vehicleModel:l.vehicle_model,vehicleCategory:l.vehicle_category||'car',itemName:l.item_name,npcModel:l.npc_model,npcScenario:l.npc_scenario};Object.entries(fields).forEach(([k,v])=>document.getElementById(k).value=v||'');document.getElementById('licenseEnabled').checked=Boolean(l.enabled);show('licenseEditor');}
function createNewLicense(){App.editingId=null;document.getElementById('licenseForm').reset();document.getElementById('licenseEnabled').checked=true;show('licenseEditor');}
function saveLicense(){post('adminSaveType',{id:App.editingId,label:value('licenseName'),licenseType:value('licenseType'),price:Number(value('licensePrice')),validDays:Number(value('licenseValidity')),vehicleModel:value('vehicleModel'),vehicleCategory:value('vehicleCategory'),itemName:value('itemName'),npcModel:value('npcModel'),npcScenario:value('npcScenario'),enabled:document.getElementById('licenseEnabled').checked});}
function setNpc(id){const l=App.adminLicenses.find(x=>Number(x.id)===Number(id));post('adminSetNpc',{id,npcModel:l?.npc_model,npcScenario:l?.npc_scenario});}
function buildRoute(id){post('adminBeginBuilder',{id});closeDialog('adminMenu');} function deleteLicense(id){if(confirm('Delete this unused license type?'))post('adminDeleteType',{id});}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&App.currentDialog)closeMenu();});
