-- Optional manual migration. cm-ems also applies these changes safely at startup.
ALTER TABLE cm_ems_members ADD COLUMN IF NOT EXISTS suspended_until DATETIME NULL AFTER on_duty;
ALTER TABLE cm_ems_members ADD COLUMN IF NOT EXISTS suspension_reason VARCHAR(160) NULL AFTER suspended_until;
ALTER TABLE cm_ems_members ADD COLUMN IF NOT EXISTS suspended_by VARCHAR(64) NULL AFTER suspension_reason;

CREATE TABLE IF NOT EXISTS cm_ems_settings (setting_key VARCHAR(64) NOT NULL, setting_value LONGTEXT NOT NULL, updated_by VARCHAR(64) NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (setting_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS cm_ems_medical_reports (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, incident_id BIGINT UNSIGNED NULL, patient_cid VARCHAR(64) NOT NULL, patient_name VARCHAR(96) NOT NULL, medic_cid VARCHAR(64) NULL, medic_name VARCHAR(96) NOT NULL, hospital_id VARCHAR(48) NULL, location VARCHAR(160) NULL, injuries LONGTEXT NULL, treatment LONGTEXT NULL, medications LONGTEXT NULL, vitals LONGTEXT NULL, outcome VARCHAR(48) NOT NULL DEFAULT 'treated', billing INT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id), KEY idx_cm_ems_report_patient (patient_cid, created_at), KEY idx_cm_ems_report_incident (incident_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS cm_ems_incidents (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, incident_number VARCHAR(32) NOT NULL, caller_cid VARCHAR(64) NULL, caller_name VARCHAR(96) NOT NULL DEFAULT 'Unknown caller', emergency_type VARCHAR(48) NOT NULL DEFAULT 'medical', priority TINYINT UNSIGNED NOT NULL DEFAULT 2, patient_count SMALLINT UNSIGNED NOT NULL DEFAULT 1, coords LONGTEXT NOT NULL, postal VARCHAR(24) NULL, details VARCHAR(255) NULL, status VARCHAR(32) NOT NULL DEFAULT 'waiting', responders LONGTEXT NOT NULL, resolution VARCHAR(96) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, resolved_at TIMESTAMP NULL, PRIMARY KEY (id), UNIQUE KEY uniq_cm_ems_incident_number (incident_number), KEY idx_cm_ems_incident_status (status, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS cm_ems_reward_claims (claim_key VARCHAR(128) NOT NULL, medic_cid VARCHAR(64) NOT NULL, patient_cid VARCHAR(64) NOT NULL, amount INT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (claim_key), KEY idx_cm_ems_reward_medic (medic_cid, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
