const app=document.getElementById('app');let state=null;
const post=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json());
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(data){state=data;const c=data.club,s=data.self;document.getElementById('clubName').textContent=`${c.name} [${c.tag}]`;document.getElementById('clubMeta').textContent=c.id;document.getElementById('description').textContent=c.description||'A CM social club.';document.getElementById('accent').style.background=c.color||'#54e9ff';document.getElementById('rank').textContent=s.rank;document.getElementById('identity').textContent=`Character ID ${s.characterId}`;document.getElementById('leave').style.display=data.actions.leave?'inline-block':'none';document.getElementById('permissions').innerHTML=Object.keys(s.permissions||{}).filter(k=>s.permissions[k]).map(k=>`<span class="chip">${esc(k.replace('club.',''))}</span>`).join('')||'<span class="muted">No additional permissions</span>';document.getElementById('members').innerHTML=(data.members||[]).map(m=>{const manageable=data.actions.manageMembers&&m.character_id!==s.characterId&&!Number(m.is_leader)&&m.rank_key!=='leader';const rankOptions=data.actions.manageRanks?(data.ranks||[]).filter(r=>!Number(r.is_leader_rank)&&Number(r.tier)<Number(s.tier)).map(r=>`<option value="${esc(r.rank_key)}">${esc(r.name)}</option>`).join(''):'';return `<div class="member"><div><div class="memberName">${esc(m.label)} ${m.online?'<span class="online">● online</span>':'<span class="offline">○ offline</span>'}</div><span class="muted">${esc(m.rank_name)}</span></div>${manageable?`<div class="memberActions">${rankOptions?`<select data-rank="${esc(m.character_id)}"><option value="">Change rank</option>${rankOptions}</select>`:''}<button data-remove="${esc(m.character_id)}">Remove</button></div>`:''}</div>`}).join('')||'<p class="muted">No members found.</p>';document.getElementById('activity').innerHTML=(data.activity||[]).map(a=>`<div class="activityRow"><span>${esc(a.action.replaceAll('_',' '))}</span><small>${esc(a.target_character_id||a.actor_character_id||'')}</small></div>`).join('')||'<p class="muted">No recent activity.</p>';}
function setDoc(o){const v=o?'open':'closed';document.documentElement.dataset.cmUi=v;document.body.dataset.cmUi=v}
function hide(){app.classList.add('hidden');setDoc(false);state=null}
function show(data){if(!data||!data.club||!data.self){hide();return}setDoc(true);app.classList.remove('hidden');render(data)}
hide();
document.getElementById('close').onclick=()=>post('close');document.getElementById('refresh').onclick=()=>post('refresh');document.getElementById('leave').onclick=async()=>{if(confirm('Leave this club?'))await post('leave')};document.addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b&&confirm('Remove this member?'))post('memberAction',{action:'remove',characterId:b.dataset.remove}).then(renderResult);});document.addEventListener('change',e=>{if(e.target.matches('[data-rank]')&&e.target.value)post('memberAction',{action:'set_rank',characterId:e.target.dataset.rank,rankKey:e.target.value}).then(renderResult)});function renderResult(r){if(r&&r.ok===false)document.getElementById('status').textContent=(r.reason||'Action failed').replaceAll('_',' ')}
window.addEventListener('message',e=>{const m=e.data||{};if(m.action==='open')show(m.data);if(m.action==='data'&&state)show(m.data);if(m.action==='close')hide()});document.addEventListener('keydown',e=>{if(e.key==='Escape')post('close')});
