CmQaScenarios = {
    {
        id = 'qa.framework.smoke',
        resource = 'cm-qa',
        layer = 'server',
        kind = 'framework',
        description = 'Verify the development QA resource is enabled and responsive.',
    },
    {
        id = 'qa.client.input-smoke',
        resource = 'cm-qa',
        layer = 'client',
        kind = 'physical_input',
        description = 'Physical E press, cm-ui prompt, and physical ESC close without a fullscreen NUI.',
    },
    {
        id = 'qa.client.hold-smoke',
        resource = 'cm-qa',
        layer = 'client',
        kind = 'physical_hold',
        description = 'Physical E hold/release measurement with a bounded duration assertion and no fullscreen NUI.',
    },
    {
        id = 'qa.framework.unregistered-invisible',
        resource = 'cm-qa',
        layer = 'server',
        kind = 'framework_lifecycle',
        description = 'Server gate has no registered client and no active run; client presentation must remain inert.',
    },
    {
        id = 'qa.framework.registration-invisible',
        resource = 'cm-qa',
        layer = 'server',
        kind = 'framework_lifecycle',
        description = 'Registration alone does not assign a run or present QA UI.',
    },
    {
        id = 'qa.framework.escape-cleanup',
        resource = 'cm-qa',
        layer = 'server',
        kind = 'framework_lifecycle',
        description = 'ESC cancellation must clear the active server run and return the client to idle.',
    },
    {
        id = 'qa.framework.post-pass-cleanup',
        resource = 'cm-qa',
        layer = 'server',
        kind = 'framework_lifecycle',
        description = 'A completed client run must not leave an active server assignment.',
    },
    {
        id = 'license.card.possession.validity',
        resource = 'cm-license',
        layer = 'server',
        kind = 'owner_contract',
        description = 'Pilot contract placeholder; requires an approved license fixture/snapshot.',
    },
    {
        id = 'license.test.start_session',
        resource = 'cm-license',
        layer = 'server',
        kind = 'owner_contract',
        description = 'Pilot contract placeholder; requires a QA character fixture.',
    },
    {
        id = 'license.checkpoint.progression',
        resource = 'cm-license',
        layer = 'client',
        kind = 'client_contract',
        description = 'Requires a registered QA client and a safe license route fixture.',
    },
    {
        id = 'electrician.qa.owner-contract',
        resource = 'cm-electrician',
        layer = 'server',
        kind = 'owner_contract',
        description = 'Verify the gated Electrician QA owner contract, fixture setup, and state restoration.',
    },
    {
        id = 'electrician.shift.start_end',
        resource = 'cm-electrician',
        layer = 'server',
        kind = 'owner_contract',
        description = 'Pilot contract placeholder; requires a QA character fixture.',
    },
    {
        id = 'electrician.repair.lifecycle',
        resource = 'cm-electrician',
        layer = 'server',
        kind = 'owner_contract',
        description = 'Requires an owner-provided QA snapshot/control contract.',
    },
    {
        id = 'electrician.panel.ui',
        resource = 'cm-electrician',
        layer = 'ui',
        kind = 'ui_fixture',
        description = 'Run by tools/cm-qa/run-ui.ps1 against the preview fixture.',
    },
    {
        id = 'electrician.panel.physical-repair',
        resource = 'cm-electrician',
        layer = 'client',
        kind = 'owner_physical_pilot',
        description = 'Early physical panel repair pilot; requires an explicit electrician QA contract and fixture.',
    },
    {
        id = 'electrician.panel.early-release',
        resource = 'cm-electrician',
        layer = 'client',
        kind = 'owner_physical_pilot',
        description = 'Early release panel repair pilot; must prove no completion, reward, or progression.',
    },
    {
        id = 'electrician.panel.shock',
        resource = 'cm-electrician',
        layer = 'client',
        kind = 'owner_physical_pilot',
        description = 'Forced deterministic panel shock; must prove no completion, reward, or progression.',
    },
    {
        id = 'fishing.cast.lifecycle',
        resource = 'cm-fishing',
        layer = 'server',
        kind = 'owner_contract',
        description = 'Compatibility alias for the Fishing owner snapshot/control contract.',
    },
    {
        id = 'fishing.qa.owner-contract',
        resource = 'cm-fishing',
        layer = 'server',
        kind = 'owner_contract',
        description = 'Verify the gated Fishing QA owner contract, deterministic setup, and state restoration.',
    },
    {
        id = 'fishing.qa.blocked-cleanup',
        resource = 'cm-fishing',
        layer = 'server',
        kind = 'framework_lifecycle',
        description = 'Verify a blocked Fishing owner run clears active state before the next server scenario.',
    },
    {
        id = 'fishing.store.minigame.ui',
        resource = 'cm-fishing',
        layer = 'ui',
        kind = 'ui_fixture',
        description = 'Requires a stable fishing UI fixture before browser automation is enabled.',
    },
}
