Config = Config or {}

local DOC_IMG = 'https://docs-backend.fivem.net/weapons/%s.png'
local function img(hash) return DOC_IMG:format(hash) end

-- Seven fixed ammo types. packSize is 1 so shops can sell exactly 1 round.
Config.DefaultAmmo = {
    { itemName = 'ammo_9mm', label = '9mm Parabellum', ammoKey = 'pistol', packSize = 1, weight = 8, enabled = true, image = 'images/ammo_9mm.svg', description = 'Standard pistol round used by every regular pistol on CM.', sortOrder = 1 },
    { itemName = 'ammo_44magnum', label = '.44 Magnum Revolver Round', ammoKey = 'revolver', packSize = 1, weight = 16, enabled = true, image = 'images/ammo_44magnum.svg', description = 'High-power revolver round used by heavy revolvers only.', sortOrder = 2 },
    { itemName = 'ammo_9x19_smg', label = '9x19mm SMG Round', ammoKey = 'smg', packSize = 1, weight = 9, enabled = true, image = 'images/ammo_9x19_smg.svg', description = 'Submachine-gun round used by every SMG class weapon.', sortOrder = 3 },
    { itemName = 'ammo_556nato', label = '5.56 NATO Rifle Round', ammoKey = 'rifle', packSize = 1, weight = 13, enabled = true, image = 'images/ammo_556nato.svg', description = 'Rifle round used by every assault and carbine rifle.', sortOrder = 4 },
    { itemName = 'ammo_762nato', label = '7.62 NATO MG Belt Round', ammoKey = 'mg', packSize = 1, weight = 18, enabled = true, image = 'images/ammo_762nato.svg', description = 'Machine-gun round used by MG class weapons.', sortOrder = 5 },
    { itemName = 'ammo_12gauge', label = '12 Gauge Shotgun Shell', ammoKey = 'shotgun', packSize = 1, weight = 20, enabled = true, image = 'images/ammo_12gauge.svg', description = 'Shotgun shell used by every shotgun.', sortOrder = 6 },
    { itemName = 'ammo_308win', label = '.308 Winchester Sniper Round', ammoKey = 'sniper', packSize = 1, weight = 28, enabled = true, image = 'images/ammo_308win.svg', description = 'Sniper round used by every sniper and marksman rifle.', sortOrder = 7 },
}

-- Fixed weapon list. Damage, ammo, weight, magazine and description are config-only.
Config.DefaultWeapons = {
    { itemName = 'weapon_pistol', label = 'Pistol', weaponHash = 'WEAPON_PISTOL', group = 'pistol', ammoItem = 'ammo_9mm', damage = 26, magazineSize = 12, recoil = 0.0, durability = 100, weight = 1100, enabled = true, image = img('WEAPON_PISTOL'), description = 'Reliable semi-automatic pistol for close-range defense.', sortOrder = 1 },
    { itemName = 'weapon_pistol_mk2', label = 'Pistol Mk II', weaponHash = 'WEAPON_PISTOL_MK2', group = 'pistol', ammoItem = 'ammo_9mm', damage = 28, magazineSize = 12, recoil = 0.0, durability = 100, weight = 1200, enabled = true, image = img('WEAPON_PISTOL_MK2'), description = 'Modernized pistol with improved handling and damage.', sortOrder = 2 },
    { itemName = 'weapon_combatpistol', label = 'Combat Pistol', weaponHash = 'WEAPON_COMBATPISTOL', group = 'pistol', ammoItem = 'ammo_9mm', damage = 27, magazineSize = 12, recoil = 0.0, durability = 100, weight = 1100, enabled = true, image = img('WEAPON_COMBATPISTOL'), description = 'Duty-style pistol balanced for accuracy and speed.', sortOrder = 3 },
    { itemName = 'weapon_appistol', label = 'AP Pistol', weaponHash = 'WEAPON_APPISTOL', group = 'pistol', ammoItem = 'ammo_9mm', damage = 24, magazineSize = 18, recoil = 0.0, durability = 100, weight = 1150, enabled = true, image = img('WEAPON_APPISTOL'), description = 'Compact automatic pistol with fast fire rate.', sortOrder = 4 },
    { itemName = 'weapon_pistol50', label = 'Pistol .50', weaponHash = 'WEAPON_PISTOL50', group = 'pistol', ammoItem = 'ammo_9mm', damage = 51, magazineSize = 9, recoil = 0.0, durability = 100, weight = 1400, enabled = true, image = img('WEAPON_PISTOL50'), description = 'Heavy pistol balanced under the CM pistol ammo family.', sortOrder = 5 },
    { itemName = 'weapon_snspistol', label = 'SNS Pistol', weaponHash = 'WEAPON_SNSPISTOL', group = 'pistol', ammoItem = 'ammo_9mm', damage = 25, magazineSize = 6, recoil = 0.0, durability = 100, weight = 900, enabled = true, image = img('WEAPON_SNSPISTOL'), description = 'Small pocket pistol with low capacity.', sortOrder = 6 },
    { itemName = 'weapon_snspistol_mk2', label = 'SNS Pistol Mk II', weaponHash = 'WEAPON_SNSPISTOL_MK2', group = 'pistol', ammoItem = 'ammo_9mm', damage = 27, magazineSize = 6, recoil = 0.0, durability = 100, weight = 1000, enabled = true, image = img('WEAPON_SNSPISTOL_MK2'), description = 'Improved pocket pistol with sharper response.', sortOrder = 7 },
    { itemName = 'weapon_heavypistol', label = 'Heavy Pistol', weaponHash = 'WEAPON_HEAVYPISTOL', group = 'pistol', ammoItem = 'ammo_9mm', damage = 40, magazineSize = 18, recoil = 0.0, durability = 100, weight = 1300, enabled = true, image = img('WEAPON_HEAVYPISTOL'), description = 'Large-frame pistol with higher damage.', sortOrder = 8 },
    { itemName = 'weapon_vintagepistol', label = 'Vintage Pistol', weaponHash = 'WEAPON_VINTAGEPISTOL', group = 'pistol', ammoItem = 'ammo_9mm', damage = 30, magazineSize = 7, recoil = 0.0, durability = 100, weight = 1000, enabled = true, image = img('WEAPON_VINTAGEPISTOL'), description = 'Classic pistol with slower reload and steady damage.', sortOrder = 9 },
    { itemName = 'weapon_ceramicpistol', label = 'Ceramic Pistol', weaponHash = 'WEAPON_CERAMICPISTOL', group = 'pistol', ammoItem = 'ammo_9mm', damage = 32, magazineSize = 12, recoil = 0.0, durability = 100, weight = 900, enabled = true, image = img('WEAPON_CERAMICPISTOL'), description = 'Light ceramic pistol with clean concealed styling.', sortOrder = 10 },
    { itemName = 'weapon_marksmanpistol', label = 'Marksman Pistol', weaponHash = 'WEAPON_MARKSMANPISTOL', group = 'pistol', ammoItem = 'ammo_9mm', damage = 70, magazineSize = 1, recoil = 0.0, durability = 100, weight = 1200, enabled = true, image = img('WEAPON_MARKSMANPISTOL'), description = 'Single-shot pistol with very high burst damage.', sortOrder = 11 },
    { itemName = 'weapon_revolver', label = 'Heavy Revolver', weaponHash = 'WEAPON_REVOLVER', group = 'pistol', ammoItem = 'ammo_44magnum', damage = 70, magazineSize = 6, recoil = 0.0, durability = 100, weight = 1500, enabled = true, image = img('WEAPON_REVOLVER'), description = 'Heavy revolver using dedicated .44 Magnum rounds.', sortOrder = 12 },
    { itemName = 'weapon_revolver_mk2', label = 'Heavy Revolver Mk II', weaponHash = 'WEAPON_REVOLVER_MK2', group = 'pistol', ammoItem = 'ammo_44magnum', damage = 75, magazineSize = 6, recoil = 0.0, durability = 100, weight = 1600, enabled = true, image = img('WEAPON_REVOLVER_MK2'), description = 'Upgraded heavy revolver using dedicated .44 Magnum rounds.', sortOrder = 13 },
    { itemName = 'weapon_doubleaction', label = 'Double-Action Revolver', weaponHash = 'WEAPON_DOUBLEACTION', group = 'pistol', ammoItem = 'ammo_44magnum', damage = 68, magazineSize = 6, recoil = 0.0, durability = 100, weight = 1300, enabled = true, image = img('WEAPON_DOUBLEACTION'), description = 'Fast double-action revolver chambered for .44 Magnum.', sortOrder = 14 },
    { itemName = 'weapon_navyrevolver', label = 'Navy Revolver', weaponHash = 'WEAPON_NAVYREVOLVER', group = 'pistol', ammoItem = 'ammo_44magnum', damage = 72, magazineSize = 6, recoil = 0.0, durability = 100, weight = 1400, enabled = true, image = img('WEAPON_NAVYREVOLVER'), description = 'Old-school revolver with heavy stopping power.', sortOrder = 15 },
    { itemName = 'weapon_gadgetpistol', label = 'Perico Pistol', weaponHash = 'WEAPON_GADGETPISTOL', group = 'pistol', ammoItem = 'ammo_9mm', damage = 34, magazineSize = 1, recoil = 0.0, durability = 100, weight = 1100, enabled = true, image = img('WEAPON_GADGETPISTOL'), description = 'Compact one-shot pistol with premium styling.', sortOrder = 16 },
    { itemName = 'weapon_pistolxm3', label = 'WM 29 Pistol', weaponHash = 'WEAPON_PISTOLXM3', group = 'pistol', ammoItem = 'ammo_9mm', damage = 38, magazineSize = 12, recoil = 0.0, durability = 100, weight = 1150, enabled = true, image = img('WEAPON_PISTOLXM3'), description = 'Modern pistol balanced for civilian gun stores.', sortOrder = 17 },
    { itemName = 'weapon_microsmg', label = 'Micro SMG', weaponHash = 'WEAPON_MICROSMG', group = 'smg', ammoItem = 'ammo_9x19_smg', damage = 22, magazineSize = 16, recoil = 0.0, durability = 100, weight = 2000, enabled = true, image = img('WEAPON_MICROSMG'), description = 'Compact SMG using 9x19mm SMG rounds.', sortOrder = 18 },
    { itemName = 'weapon_smg', label = 'SMG', weaponHash = 'WEAPON_SMG', group = 'smg', ammoItem = 'ammo_9x19_smg', damage = 23, magazineSize = 30, recoil = 0.0, durability = 100, weight = 2600, enabled = true, image = img('WEAPON_SMG'), description = 'Standard submachine gun with balanced fire rate.', sortOrder = 19 },
    { itemName = 'weapon_smg_mk2', label = 'SMG Mk II', weaponHash = 'WEAPON_SMG_MK2', group = 'smg', ammoItem = 'ammo_9x19_smg', damage = 25, magazineSize = 30, recoil = 0.0, durability = 100, weight = 2700, enabled = true, image = img('WEAPON_SMG_MK2'), description = 'Improved SMG with slightly higher damage.', sortOrder = 20 },
    { itemName = 'weapon_assaultsmg', label = 'Assault SMG', weaponHash = 'WEAPON_ASSAULTSMG', group = 'smg', ammoItem = 'ammo_9x19_smg', damage = 24, magazineSize = 30, recoil = 0.0, durability = 100, weight = 2800, enabled = true, image = img('WEAPON_ASSAULTSMG'), description = 'Stable SMG for close-to-mid range fights.', sortOrder = 21 },
    { itemName = 'weapon_combatpdw', label = 'Combat PDW', weaponHash = 'WEAPON_COMBATPDW', group = 'smg', ammoItem = 'ammo_9x19_smg', damage = 25, magazineSize = 30, recoil = 0.0, durability = 100, weight = 2900, enabled = true, image = img('WEAPON_COMBATPDW'), description = 'Personal defense weapon with strong control.', sortOrder = 22 },
    { itemName = 'weapon_machinepistol', label = 'Machine Pistol', weaponHash = 'WEAPON_MACHINEPISTOL', group = 'smg', ammoItem = 'ammo_9x19_smg', damage = 21, magazineSize = 12, recoil = 0.0, durability = 100, weight = 1400, enabled = true, image = img('WEAPON_MACHINEPISTOL'), description = 'Light machine pistol with high mobility.', sortOrder = 23 },
    { itemName = 'weapon_minismg', label = 'Mini SMG', weaponHash = 'WEAPON_MINISMG', group = 'smg', ammoItem = 'ammo_9x19_smg', damage = 22, magazineSize = 20, recoil = 0.0, durability = 100, weight = 1800, enabled = true, image = img('WEAPON_MINISMG'), description = 'Small SMG with fast close-range handling.', sortOrder = 24 },
    { itemName = 'weapon_tecpistol', label = 'Tactical SMG', weaponHash = 'WEAPON_TECPISTOL', group = 'smg', ammoItem = 'ammo_9x19_smg', damage = 24, magazineSize = 18, recoil = 0.0, durability = 100, weight = 1900, enabled = true, image = img('WEAPON_TECPISTOL'), description = 'Modern tactical SMG using standard SMG rounds.', sortOrder = 25 },
    { itemName = 'weapon_assaultrifle', label = 'Assault Rifle', weaponHash = 'WEAPON_ASSAULTRIFLE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 30, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3500, enabled = true, image = img('WEAPON_ASSAULTRIFLE'), description = 'Assault rifle using shared 5.56 NATO rifle rounds.', sortOrder = 26 },
    { itemName = 'weapon_assaultrifle_mk2', label = 'Assault Rifle Mk II', weaponHash = 'WEAPON_ASSAULTRIFLE_MK2', group = 'rifle', ammoItem = 'ammo_556nato', damage = 33, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3600, enabled = true, image = img('WEAPON_ASSAULTRIFLE_MK2'), description = 'Upgraded assault rifle using 5.56 NATO rounds.', sortOrder = 27 },
    { itemName = 'weapon_carbinerifle', label = 'Carbine Rifle', weaponHash = 'WEAPON_CARBINERIFLE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 32, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3700, enabled = true, image = img('WEAPON_CARBINERIFLE'), description = 'Stable carbine rifle using 5.56 NATO rounds.', sortOrder = 28 },
    { itemName = 'weapon_carbinerifle_mk2', label = 'Carbine Rifle Mk II', weaponHash = 'WEAPON_CARBINERIFLE_MK2', group = 'rifle', ammoItem = 'ammo_556nato', damage = 34, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3800, enabled = true, image = img('WEAPON_CARBINERIFLE_MK2'), description = 'Upgraded carbine rifle using 5.56 NATO rounds.', sortOrder = 29 },
    { itemName = 'weapon_advancedrifle', label = 'Advanced Rifle', weaponHash = 'WEAPON_ADVANCEDRIFLE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 30, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3400, enabled = true, image = img('WEAPON_ADVANCEDRIFLE'), description = 'Compact advanced rifle with balanced recoil.', sortOrder = 30 },
    { itemName = 'weapon_specialcarbine', label = 'Special Carbine', weaponHash = 'WEAPON_SPECIALCARBINE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 32, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3600, enabled = true, image = img('WEAPON_SPECIALCARBINE'), description = 'Versatile rifle with good handling.', sortOrder = 31 },
    { itemName = 'weapon_specialcarbine_mk2', label = 'Special Carbine Mk II', weaponHash = 'WEAPON_SPECIALCARBINE_MK2', group = 'rifle', ammoItem = 'ammo_556nato', damage = 34, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3700, enabled = true, image = img('WEAPON_SPECIALCARBINE_MK2'), description = 'Upgraded special carbine with better response.', sortOrder = 32 },
    { itemName = 'weapon_bullpuprifle', label = 'Bullpup Rifle', weaponHash = 'WEAPON_BULLPUPRIFLE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 30, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3400, enabled = true, image = img('WEAPON_BULLPUPRIFLE'), description = 'Short rifle with quick handling.', sortOrder = 33 },
    { itemName = 'weapon_bullpuprifle_mk2', label = 'Bullpup Rifle Mk II', weaponHash = 'WEAPON_BULLPUPRIFLE_MK2', group = 'rifle', ammoItem = 'ammo_556nato', damage = 32, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3500, enabled = true, image = img('WEAPON_BULLPUPRIFLE_MK2'), description = 'Upgraded bullpup rifle using 5.56 NATO.', sortOrder = 34 },
    { itemName = 'weapon_compactrifle', label = 'Compact Rifle', weaponHash = 'WEAPON_COMPACTRIFLE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 29, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3000, enabled = true, image = img('WEAPON_COMPACTRIFLE'), description = 'Compact rifle with high mobility.', sortOrder = 35 },
    { itemName = 'weapon_militaryrifle', label = 'Military Rifle', weaponHash = 'WEAPON_MILITARYRIFLE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 34, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3700, enabled = true, image = img('WEAPON_MILITARYRIFLE'), description = 'Military-style rifle using shared rifle ammo.', sortOrder = 36 },
    { itemName = 'weapon_heavyrifle', label = 'Heavy Rifle', weaponHash = 'WEAPON_HEAVYRIFLE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 36, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3800, enabled = true, image = img('WEAPON_HEAVYRIFLE'), description = 'Heavy rifle with higher per-bullet damage.', sortOrder = 37 },
    { itemName = 'weapon_battlerifle', label = 'Battle Rifle', weaponHash = 'WEAPON_BATTLERIFLE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 35, magazineSize = 20, recoil = 0.0, durability = 100, weight = 3700, enabled = true, image = img('WEAPON_BATTLERIFLE'), description = 'Battle rifle balanced under the shared rifle ammo family.', sortOrder = 38 },
    { itemName = 'weapon_tacticalrifle', label = 'Service Carbine', weaponHash = 'WEAPON_TACTICALRIFLE', group = 'rifle', ammoItem = 'ammo_556nato', damage = 32, magazineSize = 30, recoil = 0.0, durability = 100, weight = 3600, enabled = true, image = img('WEAPON_TACTICALRIFLE'), description = 'Service carbine with clean mid-range performance.', sortOrder = 39 },
    { itemName = 'weapon_pumpshotgun', label = 'Pump Shotgun', weaponHash = 'WEAPON_PUMPSHOTGUN', group = 'shotgun', ammoItem = 'ammo_12gauge', damage = 60, magazineSize = 8, recoil = 0.0, durability = 100, weight = 3800, enabled = true, image = img('WEAPON_PUMPSHOTGUN'), description = 'Pump-action shotgun using 12 gauge shells.', sortOrder = 40 },
    { itemName = 'weapon_pumpshotgun_mk2', label = 'Pump Shotgun Mk II', weaponHash = 'WEAPON_PUMPSHOTGUN_MK2', group = 'shotgun', ammoItem = 'ammo_12gauge', damage = 64, magazineSize = 8, recoil = 0.0, durability = 100, weight = 3900, enabled = true, image = img('WEAPON_PUMPSHOTGUN_MK2'), description = 'Upgraded pump shotgun using 12 gauge shells.', sortOrder = 41 },
    { itemName = 'weapon_sawnoffshotgun', label = 'Sawed-Off Shotgun', weaponHash = 'WEAPON_SAWNOFFSHOTGUN', group = 'shotgun', ammoItem = 'ammo_12gauge', damage = 75, magazineSize = 2, recoil = 0.0, durability = 100, weight = 3000, enabled = true, image = img('WEAPON_SAWNOFFSHOTGUN'), description = 'Shortened shotgun with strong close-range damage.', sortOrder = 42 },
    { itemName = 'weapon_assaultshotgun', label = 'Assault Shotgun', weaponHash = 'WEAPON_ASSAULTSHOTGUN', group = 'shotgun', ammoItem = 'ammo_12gauge', damage = 55, magazineSize = 8, recoil = 0.0, durability = 100, weight = 4000, enabled = true, image = img('WEAPON_ASSAULTSHOTGUN'), description = 'Automatic shotgun using 12 gauge shells.', sortOrder = 43 },
    { itemName = 'weapon_bullpupshotgun', label = 'Bullpup Shotgun', weaponHash = 'WEAPON_BULLPUPSHOTGUN', group = 'shotgun', ammoItem = 'ammo_12gauge', damage = 58, magazineSize = 14, recoil = 0.0, durability = 100, weight = 3900, enabled = true, image = img('WEAPON_BULLPUPSHOTGUN'), description = 'Bullpup shotgun with higher shell capacity.', sortOrder = 44 },
    { itemName = 'weapon_heavyshotgun', label = 'Heavy Shotgun', weaponHash = 'WEAPON_HEAVYSHOTGUN', group = 'shotgun', ammoItem = 'ammo_12gauge', damage = 62, magazineSize = 12, recoil = 0.0, durability = 100, weight = 4200, enabled = true, image = img('WEAPON_HEAVYSHOTGUN'), description = 'Heavy shotgun with strong close-range control.', sortOrder = 45 },
    { itemName = 'weapon_dbshotgun', label = 'Double Barrel Shotgun', weaponHash = 'WEAPON_DBSHOTGUN', group = 'shotgun', ammoItem = 'ammo_12gauge', damage = 80, magazineSize = 2, recoil = 0.0, durability = 100, weight = 3200, enabled = true, image = img('WEAPON_DBSHOTGUN'), description = 'Double barrel shotgun with extreme burst damage.', sortOrder = 46 },
    { itemName = 'weapon_autoshotgun', label = 'Sweeper Shotgun', weaponHash = 'WEAPON_AUTOSHOTGUN', group = 'shotgun', ammoItem = 'ammo_12gauge', damage = 54, magazineSize = 10, recoil = 0.0, durability = 100, weight = 3600, enabled = true, image = img('WEAPON_AUTOSHOTGUN'), description = 'Compact automatic shotgun for close quarters.', sortOrder = 47 },
    { itemName = 'weapon_combatshotgun', label = 'Combat Shotgun', weaponHash = 'WEAPON_COMBATSHOTGUN', group = 'shotgun', ammoItem = 'ammo_12gauge', damage = 60, magazineSize = 6, recoil = 0.0, durability = 100, weight = 3800, enabled = true, image = img('WEAPON_COMBATSHOTGUN'), description = 'Combat shotgun with fast follow-up shots.', sortOrder = 48 },
    { itemName = 'weapon_sniperrifle', label = 'Sniper Rifle', weaponHash = 'WEAPON_SNIPERRIFLE', group = 'sniper', ammoItem = 'ammo_308win', damage = 101, magazineSize = 10, recoil = 0.0, durability = 100, weight = 5000, enabled = true, image = img('WEAPON_SNIPERRIFLE'), description = 'Precision sniper rifle using .308 Winchester rounds.', sortOrder = 49 },
    { itemName = 'weapon_heavysniper', label = 'Heavy Sniper', weaponHash = 'WEAPON_HEAVYSNIPER', group = 'sniper', ammoItem = 'ammo_308win', damage = 150, magazineSize = 6, recoil = 0.0, durability = 100, weight = 5500, enabled = true, image = img('WEAPON_HEAVYSNIPER'), description = 'Heavy sniper using shared sniper rounds.', sortOrder = 50 },
    { itemName = 'weapon_heavysniper_mk2', label = 'Heavy Sniper Mk II', weaponHash = 'WEAPON_HEAVYSNIPER_MK2', group = 'sniper', ammoItem = 'ammo_308win', damage = 160, magazineSize = 6, recoil = 0.0, durability = 100, weight = 5600, enabled = true, image = img('WEAPON_HEAVYSNIPER_MK2'), description = 'Upgraded heavy sniper using shared sniper rounds.', sortOrder = 51 },
    { itemName = 'weapon_marksmanrifle', label = 'Marksman Rifle', weaponHash = 'WEAPON_MARKSMANRIFLE', group = 'sniper', ammoItem = 'ammo_308win', damage = 65, magazineSize = 8, recoil = 0.0, durability = 100, weight = 4800, enabled = true, image = img('WEAPON_MARKSMANRIFLE'), description = 'Semi-automatic marksman rifle using sniper rounds.', sortOrder = 52 },
    { itemName = 'weapon_marksmanrifle_mk2', label = 'Marksman Rifle Mk II', weaponHash = 'WEAPON_MARKSMANRIFLE_MK2', group = 'sniper', ammoItem = 'ammo_308win', damage = 70, magazineSize = 8, recoil = 0.0, durability = 100, weight = 4900, enabled = true, image = img('WEAPON_MARKSMANRIFLE_MK2'), description = 'Upgraded marksman rifle using sniper rounds.', sortOrder = 53 },
    { itemName = 'weapon_precisionrifle', label = 'Precision Rifle', weaponHash = 'WEAPON_PRECISIONRIFLE', group = 'sniper', ammoItem = 'ammo_308win', damage = 95, magazineSize = 10, recoil = 0.0, durability = 100, weight = 5000, enabled = true, image = img('WEAPON_PRECISIONRIFLE'), description = 'Precision rifle tuned for accurate long-range shots.', sortOrder = 54 },
    { itemName = 'weapon_mg', label = 'MG', weaponHash = 'WEAPON_MG', group = 'machinegun', ammoItem = 'ammo_762nato', damage = 30, magazineSize = 54, recoil = 0.0, durability = 100, weight = 5200, enabled = true, image = img('WEAPON_MG'), description = 'Machine gun using 7.62 NATO belt rounds.', sortOrder = 55 },
    { itemName = 'weapon_combatmg', label = 'Combat MG', weaponHash = 'WEAPON_COMBATMG', group = 'machinegun', ammoItem = 'ammo_762nato', damage = 32, magazineSize = 100, recoil = 0.0, durability = 100, weight = 5600, enabled = true, image = img('WEAPON_COMBATMG'), description = 'Combat machine gun with large belt capacity.', sortOrder = 56 },
    { itemName = 'weapon_combatmg_mk2', label = 'Combat MG Mk II', weaponHash = 'WEAPON_COMBATMG_MK2', group = 'machinegun', ammoItem = 'ammo_762nato', damage = 34, magazineSize = 100, recoil = 0.0, durability = 100, weight = 5700, enabled = true, image = img('WEAPON_COMBATMG_MK2'), description = 'Upgraded machine gun using 7.62 NATO rounds.', sortOrder = 57 },
    { itemName = 'weapon_gusenberg', label = 'Gusenberg Sweeper', weaponHash = 'WEAPON_GUSENBERG', group = 'machinegun', ammoItem = 'ammo_762nato', damage = 34, magazineSize = 30, recoil = 0.0, durability = 100, weight = 4500, enabled = true, image = img('WEAPON_GUSENBERG'), description = 'Classic drum-fed machine gun using MG ammo.', sortOrder = 58 },
    { itemName = 'weapon_minigun', label = 'Minigun', weaponHash = 'WEAPON_MINIGUN', group = 'machinegun', ammoItem = 'ammo_762nato', damage = 30, magazineSize = 250, recoil = 0.0, durability = 100, weight = 9000, enabled = false, image = img('WEAPON_MINIGUN'), description = 'Heavy machine gun class weapon; disabled by default for normal stores.', sortOrder = 59 },
}

Config.FixedAmmoIndex = {}
for _, ammo in ipairs(Config.DefaultAmmo or {}) do Config.FixedAmmoIndex[ammo.itemName] = ammo end
Config.FixedWeaponIndex = {}
for _, weapon in ipairs(Config.DefaultWeapons or {}) do Config.FixedWeaponIndex[weapon.itemName] = weapon end