local L0_1, L1_1, L2_1
L0_1 = IsDuplicityVersion
L0_1 = L0_1()
if not L0_1 then
  return
end
L0_1 = "-- This part is generated by sv-deployer.lua from %s"
L1_1 = L0_1
L0_1 = L0_1.format
L2_1 = GetCurrentResourceName
L2_1 = L2_1()
L0_1 = L0_1(L1_1, L2_1)
ASSET_DEPLOYER_WATERMARK_PREFIX = L0_1
ASSET_DEPLOYER_WATERMARK_SUFFIX = "-- Do not edit this part manually unless you know what you are doing"
function L0_1(A0_2, ...)
  local L1_2, L2_2, L3_2, L4_2
  L1_2 = A0_2
  L2_2 = table
  L2_2 = L2_2.concat
  L3_2 = {}
  L4_2 = ...
  L3_2[1] = L4_2
  L4_2 = "\n"
  L2_2 = L2_2(L3_2, L4_2)
  L1_2 = L1_2 .. L2_2
  return L1_2
end
append = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2
  L2_2 = LoadResourceFile
  L3_2 = A0_2
  L4_2 = A1_2
  return L2_2(L3_2, L4_2)
end
loadFile = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "QBShared.Items = {"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = "\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendQB = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "%['jailbeds'%] = {"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = ",\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendQBHospitalBeds = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "eat = {"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = ",\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendQBConsumablesEat = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "%(ContactData%.number%)"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = "\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendQBPhoneTarget = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "%(playerId, time%)"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = "\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendQBJailEvent = L0_1
function L0_1(A0_2)
  local L1_2, L2_2, L3_2, L4_2
  L2_2 = A0_2
  L1_2 = A0_2.strtrim
  L1_2 = L1_2(L2_2)
  A0_2 = L1_2
  L2_2 = A0_2
  L1_2 = A0_2.gsub
  L3_2 = "QBCore.Commands.Add%('jail'.-end%)"
  L4_2 = ""
  L1_2 = L1_2(L2_2, L3_2, L4_2)
  A0_2 = L1_2
  return A0_2
end
appendQBJailCommand = L0_1
function L0_1(A0_2)
  local L1_2, L2_2, L3_2, L4_2
  L2_2 = A0_2
  L1_2 = A0_2.strtrim
  L1_2 = L1_2(L2_2)
  A0_2 = L1_2
  L2_2 = A0_2
  L1_2 = A0_2.gsub
  L3_2 = "QBCore.Commands.Add%('unjail'.-end%)"
  L4_2 = ""
  L1_2 = L1_2(L2_2, L3_2, L4_2)
  A0_2 = L1_2
  return A0_2
end
appendQBUnjailCommand = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "drink = {"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = ",\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendQBConsumablesDrink = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "return {"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = "\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendAfterReturn = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "BasketballHoops = {"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = "\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendBasketBallHoops = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "Config.Items = {"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = "\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendESXBasicNeedsAfterItems = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2
  L3_2 = A0_2
  L2_2 = A0_2.strtrim
  L2_2 = L2_2(L3_2)
  A0_2 = L2_2
  L3_2 = A0_2
  L2_2 = A0_2.gsub
  L4_2 = "return {"
  function L5_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3
    L1_3 = A0_3
    L2_3 = "\n"
    L3_3 = A1_2
    L4_3 = "\n"
    L1_3 = L1_3 .. L2_3 .. L3_3 .. L4_3
    return L1_3
  end
  return L2_2(L3_2, L4_2, L5_2)
end
appendQBDoorLock = L0_1
function L0_1(A0_2, A1_2)
  local L2_2, L3_2, L4_2, L5_2, L6_2, L7_2, L8_2, L9_2, L10_2, L11_2, L12_2, L13_2, L14_2, L15_2, L16_2, L17_2, L18_2, L19_2, L20_2, L21_2, L22_2, L23_2, L24_2, L25_2, L26_2, L27_2, L28_2, L29_2, L30_2, L31_2, L32_2, L33_2, L34_2
  L2_2 = isResourceLoaded
  L3_2 = A0_2
  L2_2 = L2_2(L3_2)
  if not L2_2 then
    L2_2 = afprint
    L3_2 = "^1[%s]^7 Resource is not loaded."
    L4_2 = Levels
    L4_2 = L4_2.ERROR
    L5_2 = A0_2
    L2_2(L3_2, L4_2, L5_2)
    return
  end
  L2_2 = afprint
  L3_2 = "^3[%s]^7 Deploying resource..."
  L4_2 = Levels
  L4_2 = L4_2.LOAD
  L5_2 = A0_2
  L2_2(L3_2, L4_2, L5_2)
  L2_2 = pairs
  L3_2 = A1_2
  L2_2, L3_2, L4_2, L5_2 = L2_2(L3_2)
  for L6_2, L7_2 in L2_2, L3_2, L4_2, L5_2 do
    L8_2 = afprint
    L9_2 = "^3[%s:%s]^7 Processing..."
    L10_2 = Levels
    L10_2 = L10_2.LOAD
    L11_2 = A0_2
    L12_2 = L6_2
    L8_2(L9_2, L10_2, L11_2, L12_2)
    L8_2 = L7_2.type
    if "file" == L8_2 then
      L8_2 = loadFile
      L9_2 = A0_2
      L10_2 = L7_2.path
      L8_2 = L8_2(L9_2, L10_2)
      L9_2 = L7_2.callback
      L10_2 = L8_2
      L11_2 = L7_2.callbackData
      L9_2 = L9_2(L10_2, L11_2)
      if L9_2 then
        L10_2 = SaveResourceFile
        L11_2 = A0_2
        L12_2 = L7_2.path
        L13_2 = L9_2
        L14_2 = -1
        L10_2(L11_2, L12_2, L13_2, L14_2)
        L10_2 = afprint
        L11_2 = "^2[%s:%s]^7 Successfully saved to %s."
        L12_2 = Levels
        L12_2 = L12_2.INFO
        L13_2 = A0_2
        L14_2 = L6_2
        L15_2 = L7_2.path
        L10_2(L11_2, L12_2, L13_2, L14_2, L15_2)
      else
        L10_2 = afprint
        L11_2 = "^1[%s:%s]^7 Deploy was not successful."
        L12_2 = Levels
        L12_2 = L12_2.ERROR
        L13_2 = A0_2
        L14_2 = L6_2
        L10_2(L11_2, L12_2, L13_2, L14_2)
      end
    else
      L8_2 = L7_2.type
      if "basic" == L8_2 then
        L8_2 = L7_2.callback
        L9_2 = L7_2.callbackData
        L8_2, L9_2 = L8_2(L9_2)
        if not L8_2 then
          L10_2 = afprint
          L11_2 = "^1[%s:%s]^7 Deploy was not successful: %s"
          L12_2 = Levels
          L12_2 = L12_2.ERROR
          L13_2 = A0_2
          L14_2 = L6_2
          L15_2 = L9_2
          L10_2(L11_2, L12_2, L13_2, L14_2, L15_2)
        end
      else
        L8_2 = L7_2.type
        if "copy-files" == L8_2 then
          L8_2 = L7_2.source
          L9_2 = L7_2.target
          L10_2 = L7_2.callback
          L11_2 = L7_2.callbackData
          L10_2 = L10_2(L11_2)
          L11_2 = GetResourcePath
          L12_2 = GetCurrentResourceName
          L12_2, L13_2, L14_2, L15_2, L16_2, L17_2, L18_2, L19_2, L20_2, L21_2, L22_2, L23_2, L24_2, L25_2, L26_2, L27_2, L28_2, L29_2, L30_2, L31_2, L32_2, L33_2, L34_2 = L12_2()
          L11_2 = L11_2(L12_2, L13_2, L14_2, L15_2, L16_2, L17_2, L18_2, L19_2, L20_2, L21_2, L22_2, L23_2, L24_2, L25_2, L26_2, L27_2, L28_2, L29_2, L30_2, L31_2, L32_2, L33_2, L34_2)
          L12_2 = GetResourcePath
          L13_2 = A0_2
          L12_2 = L12_2(L13_2)
          L13_2 = ipairs
          L14_2 = L10_2
          L13_2, L14_2, L15_2, L16_2 = L13_2(L14_2)
          for L17_2, L18_2 in L13_2, L14_2, L15_2, L16_2 do
            L19_2 = string
            L19_2 = L19_2.format
            L20_2 = "%s/%s/%s"
            L21_2 = L11_2
            L22_2 = L8_2
            L23_2 = L18_2
            L19_2 = L19_2(L20_2, L21_2, L22_2, L23_2)
            L20_2 = io
            L20_2 = L20_2.open
            L21_2 = L19_2
            L22_2 = "rb"
            L20_2 = L20_2(L21_2, L22_2)
            if nil == L20_2 then
              L21_2 = afprint
              L22_2 = "^1[%s:%s]^7 Source file %s/%s does not exist in resource %s."
              L23_2 = Levels
              L23_2 = L23_2.ERROR
              L24_2 = A0_2
              L25_2 = L6_2
              L26_2 = L8_2
              L27_2 = L18_2
              L28_2 = GetCurrentResourceName
              L28_2, L29_2, L30_2, L31_2, L32_2, L33_2, L34_2 = L28_2()
              L21_2(L22_2, L23_2, L24_2, L25_2, L26_2, L27_2, L28_2, L29_2, L30_2, L31_2, L32_2, L33_2, L34_2)
            else
              L22_2 = L20_2
              L21_2 = L20_2.read
              L23_2 = "*a"
              L21_2 = L21_2(L22_2, L23_2)
              L23_2 = L20_2
              L22_2 = L20_2.close
              L22_2(L23_2)
              L22_2 = string
              L22_2 = L22_2.format
              L23_2 = "%s/%s/%s"
              L24_2 = L12_2
              L25_2 = L9_2
              L26_2 = L18_2
              L22_2 = L22_2(L23_2, L24_2, L25_2, L26_2)
              L23_2 = io
              L23_2 = L23_2.open
              L24_2 = L22_2
              L25_2 = "wb"
              L23_2 = L23_2(L24_2, L25_2)
              if nil == L23_2 then
                L24_2 = afprint
                L25_2 = "^1[%s:%s]^7 Target file %s/%s does not exist in resource %s."
                L26_2 = Levels
                L26_2 = L26_2.ERROR
                L27_2 = A0_2
                L28_2 = L6_2
                L29_2 = L9_2
                L30_2 = L18_2
                L31_2 = A0_2
                L24_2(L25_2, L26_2, L27_2, L28_2, L29_2, L30_2, L31_2)
              else
                L25_2 = L23_2
                L24_2 = L23_2.write
                L26_2 = L21_2
                L24_2(L25_2, L26_2)
                L25_2 = L23_2
                L24_2 = L23_2.close
                L24_2(L25_2)
                L24_2 = afprint
                L25_2 = "^2[%s:%s]^7 Successfully copied %s from %s to %s."
                L26_2 = Levels
                L26_2 = L26_2.INFO
                L27_2 = A0_2
                L28_2 = L6_2
                L29_2 = L18_2
                L30_2 = string
                L30_2 = L30_2.format
                L31_2 = "%s/%s/"
                L32_2 = GetCurrentResourceName
                L32_2 = L32_2()
                L33_2 = L8_2
                L30_2 = L30_2(L31_2, L32_2, L33_2)
                L31_2 = string
                L31_2 = L31_2.format
                L32_2 = "%s/%s/"
                L33_2 = A0_2
                L34_2 = L9_2
                L31_2, L32_2, L33_2, L34_2 = L31_2(L32_2, L33_2, L34_2)
                L24_2(L25_2, L26_2, L27_2, L28_2, L29_2, L30_2, L31_2, L32_2, L33_2, L34_2)
              end
            end
          end
        end
      end
    end
    L8_2 = afprint
    L9_2 = "^2[%s:%s]^7 Successfully processed."
    L10_2 = Levels
    L10_2 = L10_2.INFO
    L11_2 = A0_2
    L12_2 = L6_2
    L8_2(L9_2, L10_2, L11_2, L12_2)
  end
  L2_2 = afprint
  L3_2 = "^2[%s]^7 Successfully deployed resource."
  L4_2 = Levels
  L4_2 = L4_2.INFO
  L5_2 = A0_2
  L2_2(L3_2, L4_2, L5_2)
  L2_2 = true
  return L2_2
end
resolveDeploy = L0_1
function L0_1()
  local L0_2, L1_2
  L0_2 = {}
  L1_2 = {}
  L0_2.deploys = L1_2
  L1_2 = {}
  L0_2.deploysCache = L1_2
  L0_2.command = nil
  L0_2.resetDeployCommand = nil
  L0_2.saveDeployInCache = false
  function L1_2(A0_3, A1_3, A2_3, A3_3, A4_3, A5_3)
    local L6_3, L7_3, L8_3
    if not A2_3 then
      return
    end
    L6_3 = A0_3.deploys
    L6_3 = L6_3[A2_3]
    if not L6_3 then
      L6_3 = A0_3.deploys
      L7_3 = {}
      L6_3[A2_3] = L7_3
    end
    L6_3 = A0_3.deploys
    L6_3 = L6_3[A2_3]
    L7_3 = {}
    L7_3.type = "file"
    L7_3.path = A3_3
    L7_3.callback = A4_3
    L8_3 = A5_3 or L8_3
    if not A5_3 then
      L8_3 = {}
    end
    L7_3.callbackData = L8_3
    L6_3[A1_3] = L7_3
  end
  L0_2.registerFileDeploy = L1_2
  function L1_2(A0_3, A1_3, A2_3, A3_3, A4_3)
    local L5_3, L6_3, L7_3
    L5_3 = A0_3.deploys
    L5_3 = L5_3[A2_3]
    if not L5_3 then
      L5_3 = A0_3.deploys
      L6_3 = {}
      L5_3[A2_3] = L6_3
    end
    L5_3 = A0_3.deploys
    L5_3 = L5_3[A2_3]
    L6_3 = {}
    L6_3.type = "basic"
    L6_3.callback = A3_3
    L7_3 = A4_3 or L7_3
    if not A4_3 then
      L7_3 = {}
    end
    L6_3.callbackData = L7_3
    L5_3[A1_3] = L6_3
  end
  L0_2.registerDeploy = L1_2
  function L1_2(A0_3, A1_3, A2_3, A3_3, A4_3, A5_3, A6_3)
    local L7_3, L8_3, L9_3
    L7_3 = A0_3.deploys
    L7_3 = L7_3[A2_3]
    if not L7_3 then
      L7_3 = A0_3.deploys
      L8_3 = {}
      L7_3[A2_3] = L8_3
    end
    L7_3 = A0_3.deploys
    L7_3 = L7_3[A2_3]
    L8_3 = {}
    L8_3.type = "copy-files"
    L8_3.source = A3_3
    L8_3.target = A4_3
    L8_3.callback = A5_3
    L9_3 = A6_3 or L9_3
    if not A6_3 then
      L9_3 = {}
    end
    L8_3.callbackData = L9_3
    L7_3[A1_3] = L8_3
  end
  L0_2.registerCopyFilesDeploy = L1_2
  function L1_2(A0_3, A1_3, A2_3)
    local L3_3, L4_3, L5_3, L6_3, L7_3
    L3_3 = A0_3.saveDeployInCache
    if L3_3 then
      L4_3 = A0_3
      L3_3 = A0_3.getDeployStateForResource
      L5_3 = A1_3
      L3_3 = L3_3(L4_3, L5_3)
      if L3_3 then
        L4_3 = afprint
        L5_3 = "^1[%s]^7 Resource is already deployed."
        L6_3 = Levels
        L6_3 = L6_3.ERROR
        L7_3 = A1_3
        return L4_3(L5_3, L6_3, L7_3)
      end
    end
    L3_3 = resolveDeploy
    L4_3 = A1_3
    L5_3 = {}
    L6_3 = A0_3.deploys
    L6_3 = L6_3[A1_3]
    L6_3 = L6_3[A2_3]
    L5_3[A2_3] = L6_3
    return L3_3(L4_3, L5_3)
  end
  L0_2.deployResourceSpecific = L1_2
  function L1_2(A0_3, A1_3)
    local L2_3, L3_3, L4_3, L5_3, L6_3
    L2_3 = A0_3.saveDeployInCache
    if L2_3 then
      L3_3 = A0_3
      L2_3 = A0_3.getDeployStateForResource
      L4_3 = A1_3
      L2_3 = L2_3(L3_3, L4_3)
      if L2_3 then
        L3_3 = afprint
        L4_3 = "^1[%s]^7 Resource is already deployed."
        L5_3 = Levels
        L5_3 = L5_3.ERROR
        L6_3 = A1_3
        return L3_3(L4_3, L5_3, L6_3)
      end
    end
    L2_3 = resolveDeploy
    L3_3 = A1_3
    L4_3 = A0_3.deploys
    L4_3 = L4_3[A1_3]
    return L2_3(L3_3, L4_3)
  end
  L0_2.deployResource = L1_2
  function L1_2(A0_3, A1_3)
    local L2_3, L3_3, L4_3, L5_3, L6_3
    L2_3 = A1_3 or nil
    if A1_3 then
      L2_3 = "%s_%s_%s"
      L3_3 = L2_3
      L2_3 = L2_3.format
      L4_3 = GetCurrentResourceName
      L4_3 = L4_3()
      L5_3 = "deployer"
      L6_3 = A1_3
      L2_3 = L2_3(L3_3, L4_3, L5_3, L6_3)
    end
    return L2_3
  end
  L0_2.getDeployCacheNamePrefix = L1_2
  function L1_2(A0_3, A1_3)
    local L2_3, L3_3, L4_3, L5_3, L6_3
    L2_3 = false
    if A1_3 then
      L3_3 = GetResourceKvpInt
      L5_3 = A0_3
      L4_3 = A0_3.getDeployCacheNamePrefix
      L6_3 = A1_3
      L4_3, L5_3, L6_3 = L4_3(L5_3, L6_3)
      L3_3 = L3_3(L4_3, L5_3, L6_3)
      if 1 == L3_3 then
        L2_3 = true
      end
    end
    return L2_3
  end
  L0_2.getDeployStateForResource = L1_2
  function L1_2(A0_3, A1_3, A2_3)
    local L3_3, L4_3, L5_3, L6_3, L7_3, L8_3, L9_3
    L4_3 = A0_3
    L3_3 = A0_3.getDeployCacheNamePrefix
    L5_3 = A1_3
    L3_3 = L3_3(L4_3, L5_3)
    if L3_3 then
      L4_3 = SetResourceKvpInt
      L5_3 = L3_3
      L6_3 = A2_3
      L4_3(L5_3, L6_3)
    end
    if 1 == A2_3 then
      L4_3 = afprint
      L5_3 = "Resource ^3%s^7 deploy was successfully cached into KVP."
      L6_3 = Levels
      L6_3 = L6_3.INFO
      L7_3 = A1_3
      L4_3(L5_3, L6_3, L7_3)
    elseif 0 == A2_3 then
      L4_3 = afprint
      L5_3 = "Resource ^3%s^7 deploy was succesfully restarted, could be deployed again via command: (/%s %s)"
      L6_3 = Levels
      L6_3 = L6_3.LOAD
      L7_3 = A1_3
      L8_3 = A0_3.command
      L9_3 = A1_3
      L4_3(L5_3, L6_3, L7_3, L8_3, L9_3)
    end
  end
  L0_2.setDeployStateIntoCache = L1_2
  function L1_2(A0_3, A1_3, A2_3)
    local L3_3, L4_3, L5_3, L6_3
    L4_3 = A0_3
    L3_3 = A0_3.getDeployCacheNamePrefix
    L5_3 = A1_3
    L3_3 = L3_3(L4_3, L5_3)
    if L3_3 then
      L4_3 = SetResourceKvpInt
      L5_3 = L3_3
      L6_3 = 0
      L4_3(L5_3, L6_3)
    end
  end
  L0_2.deleteKvpByReourceName = L1_2
  function L1_2(A0_3)
    local L1_3, L2_3, L3_3, L4_3, L5_3, L6_3, L7_3, L8_3, L9_3, L10_3, L11_3, L12_3, L13_3, L14_3, L15_3
    L1_3 = promise
    L1_3 = L1_3.new
    L1_3 = L1_3()
    L2_3 = next
    L3_3 = A0_3.deploys
    L2_3 = L2_3(L3_3)
    if L2_3 then
      L2_3 = table
      L2_3 = L2_3.len
      L3_3 = A0_3.deploys
      L2_3 = L2_3(L3_3)
      L3_3 = 0
      L4_3 = pairs
      L5_3 = A0_3.deploys
      L4_3, L5_3, L6_3, L7_3 = L4_3(L5_3)
      for L8_3, L9_3 in L4_3, L5_3, L6_3, L7_3 do
        L3_3 = L3_3 + 1
        if L8_3 then
          L11_3 = A0_3
          L10_3 = A0_3.getDeployStateForResource
          L12_3 = L8_3
          L10_3 = L10_3(L11_3, L12_3)
          if L10_3 then
            L11_3 = A0_3.deploysCache
            L12_3 = {}
            L12_3.state = L10_3
            L14_3 = A0_3
            L13_3 = A0_3.getDeployCacheNamePrefix
            L15_3 = L8_3
            L13_3 = L13_3(L14_3, L15_3)
            L12_3.kvpKey = L13_3
            L11_3[L8_3] = L12_3
          end
        end
        if L2_3 <= L3_3 then
          L11_3 = L1_3
          L10_3 = L1_3.resolve
          L12_3 = true
          L10_3(L11_3, L12_3)
        end
      end
    else
      L3_3 = L1_3
      L2_3 = L1_3.resolve
      L4_3 = true
      L2_3(L3_3, L4_3)
    end
    L2_3 = Citizen
    L2_3 = L2_3.Await
    L3_3 = L1_3
    L2_3(L3_3)
    L2_3 = A0_3.deploysCache
    if L2_3 then
      L2_3 = next
      L3_3 = A0_3.deploysCache
      L2_3 = L2_3(L3_3)
      if L2_3 then
        L2_3 = afprint
        L3_3 = "Showing current cached resources into KVP storage!"
        L4_3 = Levels
        L4_3 = L4_3.LOAD
        L2_3(L3_3, L4_3)
        L2_3 = tprint
        L3_3 = A0_3.deploysCache
        L2_3(L3_3)
    end
    else
      L2_3 = afprint
      L3_3 = "The deployer KVP storage is empty!"
      L4_3 = Levels
      L4_3 = L4_3.INFO
      L2_3(L3_3, L4_3)
    end
  end
  L0_2.getDeployCache = L1_2
  function L1_2(A0_3, A1_3)
    local L2_3, L3_3, L4_3
    A0_3.saveDeployInCache = A1_3
    if A1_3 then
      L2_3 = afprint
      L3_3 = "Enabling resource deployer saving deploys into KVP storage."
      L4_3 = Levels
      L4_3 = L4_3.LOAD
      L2_3(L3_3, L4_3)
    end
  end
  L0_2.setSaveDeployInCache = L1_2
  function L1_2(A0_3, A1_3)
    local L2_3, L3_3, L4_3
    L2_3 = A1_3 or nil
    if not A1_3 then
      L2_3 = "resetdeploy"
    end
    A0_3.resetDeployCommand = L2_3
    L2_3 = RegisterCommand
    L3_3 = A1_3 or L3_3
    if not A1_3 then
      L3_3 = "resetdeploy"
    end
    function L4_3(A0_4, A1_4)
      local L2_4, L3_4, L4_4, L5_4, L6_4, L7_4
      if 0 ~= A0_4 then
        return
      end
      L2_4 = A1_4[1]
      if nil == L2_4 then
        L2_4 = afprint
        L3_4 = "Usage: /resetdeploy <resource> [name]"
        L4_4 = Levels
        L4_4 = L4_4.ERROR
        L2_4(L3_4, L4_4)
        return
      end
      L2_4 = A1_4[1]
      L3_4 = A0_3.deploys
      L3_4 = L3_4[L2_4]
      if not L3_4 then
        L3_4 = afprint
        L4_4 = "Resource %s is not registered yet."
        L5_4 = Levels
        L5_4 = L5_4.ERROR
        L6_4 = L2_4
        L3_4(L4_4, L5_4, L6_4)
        return
      end
      L3_4 = A0_3
      L4_4 = L3_4
      L3_4 = L3_4.getDeployStateForResource
      L5_4 = L2_4
      L3_4 = L3_4(L4_4, L5_4)
      if not L3_4 then
        L4_4 = afprint
        L5_4 = "Resource %s is not stored in KVP storage!"
        L6_4 = Levels
        L6_4 = L6_4.ERROR
        L7_4 = L2_4
        L4_4(L5_4, L6_4, L7_4)
        return
      end
      L4_4 = A0_3
      L5_4 = L4_4
      L4_4 = L4_4.setDeployStateIntoCache
      L6_4 = L2_4
      L7_4 = 0
      L4_4(L5_4, L6_4, L7_4)
    end
    L2_3(L3_3, L4_3)
  end
  L0_2.registerResetDeployCommand = L1_2
  function L1_2(A0_3, A1_3)
    local L2_3, L3_3, L4_3
    L2_3 = A1_3 or nil
    if not A1_3 then
      L2_3 = "deploy"
    end
    A0_3.command = L2_3
    A0_3.deployState = false
    L2_3 = RegisterCommand
    L3_3 = A1_3 or L3_3
    if not A1_3 then
      L3_3 = "deploy"
    end
    function L4_3(A0_4, A1_4)
      local L2_4, L3_4, L4_4, L5_4, L6_4, L7_4
      if 0 ~= A0_4 then
        return
      end
      L2_4 = A1_4[1]
      if nil == L2_4 then
        L2_4 = afprint
        L3_4 = "Usage: /prisonsetup <resource> [name]"
        L4_4 = Levels
        L4_4 = L4_4.ERROR
        L2_4(L3_4, L4_4)
        return
      end
      L2_4 = A1_4[1]
      L3_4 = A0_3.deploys
      L3_4 = L3_4[L2_4]
      if not L3_4 then
        L3_4 = afprint
        L4_4 = "Resource %s is not registered yet."
        L5_4 = Levels
        L5_4 = L5_4.ERROR
        L6_4 = L2_4
        L3_4(L4_4, L5_4, L6_4)
        return
      end
      L3_4 = A1_4[2]
      if nil ~= L3_4 then
        L4_4 = A0_3.deploys
        L4_4 = L4_4[L2_4]
        L4_4 = L4_4[L3_4]
        if not L4_4 then
          L4_4 = afprint
          L5_4 = "Deploy %s is not registered yet."
          L6_4 = Levels
          L6_4 = L6_4.ERROR
          L7_4 = L3_4
          L4_4(L5_4, L6_4, L7_4)
          return
        end
        L4_4 = A0_3
        L5_4 = L4_4
        L4_4 = L4_4.deployResourceSpecific
        L6_4 = L2_4
        L7_4 = L3_4
        L4_4 = L4_4(L5_4, L6_4, L7_4)
        A0_3.deployState = L4_4
        return
      end
      L4_4 = A0_3
      L5_4 = L4_4
      L4_4 = L4_4.deployResource
      L6_4 = L2_4
      L4_4 = L4_4(L5_4, L6_4)
      A0_3.deployState = L4_4
      L4_4 = A0_3.deployState
      if L4_4 then
        L4_4 = A0_3.saveDeployInCache
        if L4_4 then
          L4_4 = A0_3
          L5_4 = L4_4
          L4_4 = L4_4.setDeployStateIntoCache
          L6_4 = L2_4
          L7_4 = 1
          L4_4(L5_4, L6_4, L7_4)
        end
      end
    end
    L2_3(L3_3, L4_3)
  end
  L0_2.registerDefaultCommand = L1_2
  function L1_2(A0_3, A1_3)
    local L2_3, L3_3, L4_3, L5_3, L6_3, L7_3, L8_3, L9_3, L10_3, L11_3, L12_3, L13_3, L14_3, L15_3, L16_3, L17_3, L18_3, L19_3
    L2_3 = {}
    L3_3 = {}
    L4_3 = next
    L5_3 = A0_3.deploys
    L4_3 = L4_3(L5_3)
    if not L4_3 then
      L4_3 = afprint
      L5_3 = "No deploys are registered yet."
      L6_3 = Levels
      L6_3 = L6_3.INFO
      L4_3(L5_3, L6_3)
      return
    end
    L4_3 = pairs
    L5_3 = A0_3.deploys
    L4_3, L5_3, L6_3, L7_3 = L4_3(L5_3)
    for L8_3, L9_3 in L4_3, L5_3, L6_3, L7_3 do
      L10_3 = isResourceLoaded
      L11_3 = L8_3
      L10_3 = L10_3(L11_3)
      if L10_3 then
        L10_3 = {}
        L2_3[L8_3] = L10_3
        L10_3 = {}
        L3_3[L8_3] = L10_3
        L10_3 = pairs
        L11_3 = L9_3
        L10_3, L11_3, L12_3, L13_3 = L10_3(L11_3)
        for L14_3, L15_3 in L10_3, L11_3, L12_3, L13_3 do
          L16_3 = table
          L16_3 = L16_3.insert
          L17_3 = L2_3[L8_3]
          L18_3 = L14_3
          L16_3(L17_3, L18_3)
          L16_3 = A0_3.saveDeployInCache
          if L16_3 then
            L17_3 = A0_3
            L16_3 = A0_3.getDeployStateForResource
            L18_3 = L8_3
            L16_3 = L16_3(L17_3, L18_3)
            if L16_3 then
              L17_3 = table
              L17_3 = L17_3.insert
              L18_3 = L3_3[L8_3]
              L19_3 = L14_3
              L17_3(L18_3, L19_3)
            end
          end
        end
      end
    end
    if A1_3 then
      L4_3 = pairs
      L5_3 = L2_3
      L4_3, L5_3, L6_3, L7_3 = L4_3(L5_3)
      for L8_3, L9_3 in L4_3, L5_3, L6_3, L7_3 do
        L10_3 = table
        L10_3 = L10_3.concat
        L11_3 = L9_3
        L12_3 = "^7,^3 "
        L10_3 = L10_3(L11_3, L12_3)
        L11_3 = A0_3.saveDeployInCache
        if L11_3 then
          L12_3 = A0_3
          L11_3 = A0_3.getDeployStateForResource
          L13_3 = L8_3
          L11_3 = L11_3(L12_3, L13_3)
          if L11_3 then
            L12_3 = afprint
            L13_3 = "Resource ^3%s^7 is already deployed. Deploy reset command ^3%s^7: ^3%s^7 (/%s %s)"
            L14_3 = Levels
            L14_3 = L14_3.LOAD
            L15_3 = L8_3
            L16_3 = table
            L16_3 = L16_3.size
            L17_3 = L3_3
            L16_3 = L16_3(L17_3)
            L17_3 = L10_3
            L18_3 = A0_3.resetDeployCommand
            L19_3 = L8_3
            L12_3(L13_3, L14_3, L15_3, L16_3, L17_3, L18_3, L19_3)
          else
            L12_3 = afprint
            L13_3 = "Resource ^3%s^7 is present on server. Suggested ^3%s^7 deploys: ^3%s^7 (/%s %s)"
            L14_3 = Levels
            L14_3 = L14_3.LOAD
            L15_3 = L8_3
            L16_3 = table
            L16_3 = L16_3.size
            L17_3 = L9_3
            L16_3 = L16_3(L17_3)
            L17_3 = L10_3
            L18_3 = A0_3.command
            L19_3 = L8_3
            L12_3(L13_3, L14_3, L15_3, L16_3, L17_3, L18_3, L19_3)
          end
        else
          L11_3 = afprint
          L12_3 = "Resource ^3%s^7 is present on server. Suggested ^3%s^7 deploys: ^3%s^7 (/%s %s)"
          L13_3 = Levels
          L13_3 = L13_3.LOAD
          L14_3 = L8_3
          L15_3 = table
          L15_3 = L15_3.size
          L16_3 = L9_3
          L15_3 = L15_3(L16_3)
          L16_3 = L10_3
          L17_3 = A0_3.command
          L18_3 = L8_3
          L11_3(L12_3, L13_3, L14_3, L15_3, L16_3, L17_3, L18_3)
        end
      end
    end
    return L2_3
  end
  L0_2.suggestDeploys = L1_2
  return L0_2
end
createDeployer = L0_1
